### PR TITLE
upgrade snabbdom to 0.7.4

### PR DESCRIPTION
**Pull request by RyanHirsch**
update to latest snabbdom, is a breaking change for panel due to boolean handling

### CODE REVIEW

**Comment by nojvek** [comment]
panel tests are passing tho right ? yeah this warrants increasing the major version for panel. I'm surprised snabbdom didn't increase their major version.

**Comment by RyanHirsch** [comment]
> panel tests are passing tho right ? yeah this warrants increasing the major version for panel. I'm surprised snabbdom didn't increase their major version.

Yes the tests all pass. Snabbdom hasn’t ever released a major version 😁

**Comment by tdumitrescu** [comment]
> surprised snabbdom didn't increase their major version

before 1.0, semver allows for breaking changes

**Comment by nojvek** [comment]
image

**Pull request merged**
