### PR TITLE
Remove domPatcher.el and reset initialized flag on detachedCallback

### PR DESCRIPTION
**Pull request by tdumitrescu**
opening for @jhp

### CODE REVIEW

**Comment by jbwyme** [comment]
may want to be a bit more defensive as well: https://www.dropbox.com/s/n2x1zwf9r48c527/Screenshot%202017-01-27%2015.05.54.png?dl=0

**Comment by tdumitrescu** [comment]
How does that happen? Element never finishes initializing / never gets attached and yet somehow detachedCallback still fires?

**Comment by jbwyme** [comment]
just delete a report from here: http://josh.dev.mixpanel.org/report/3/dashboard

**Comment by tdumitrescu** [comment]
Published for expediency in 0.10.0-rc7, but let's still get these issues squared away.

**Comment by jbwyme** [comment]
thanks!!

**Pull request merged**
