### PR TITLE
bump snabbdom version to fix typescript Module interface

### PR DESCRIPTION
**Pull request by RyanHirsch**
Pull in typescript interface fix for `Module` as described here - https://github.com/snabbdom/snabbdom/releases/tag/v0.6.3

### CODE REVIEW

**Comment by tdumitrescu** [comment]
Is 0.6.4 the latest we can bump to?

**Comment by RyanHirsch** [comment]
> Is 0.6.4 the latest we can bump to?

I was able to update to latest 0.7.4 by changing
```
import snabbdom from 'snabbdom';
```
to
```
import {init} from 'snabbdom';
```

This appears to have broken with 0.6.8

**Comment by RyanHirsch** [comment]
The wct's pass for Firefox, but I'm having Selenium issues with Chrome 80 on my local box.

**Comment by tdumitrescu** [comment]
Merged via https://github.com/mixpanel/panel/pull/82/commits/ea1c2accb5db677ee2504f9e1f84fe545b8143a9 and released in v2.7.0

**Pull request closed without merging**
